service: spatialsync-websocket

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  environment:
    TABLE_NAME: spatial-sync-arjav
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}/index/*
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource:
            - arn:aws:execute-api:${self:provider.region}:*:*/@connections/*

functions:
  connect:
    handler: handlers/connect.handler
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: handlers/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  default:
    handler: handlers/default.handler
    events:
      - websocket:
          route: $default
